experiment_name: "knn"
pipeline: "knn"
cv_folds: 15
grid_cv_folds: 3
seed: 17
pipeline_params:
  thresholds: [0.01, 0.02]
  n_neighbors: [3, 5]
  power_parameter: [1, 2] # 1: Manhattan, 2: Euclidean
  impute_strategy: ["mean", "most_frequent"]
