experiment_name: "gaussian_nb_experiment2"
pipeline: "gaussian_nb"
cv_folds: 15
grid_cv_folds: 3
seed: 17
pipeline_params:
  num_top_features: [10, 15]
  selector_score_func: ["f_classif", "chi2"]
  impute_strategy: ["mean", "most_frequent"]
