experiment_name: "gaussian_nb_experiment"
pipeline: "gaussian_nb"
cv_folds: 15
grid_cv_folds: 3
seed: 17
pipeline_params:
  num_top_features: [3, 5, 10]
  selector_score_func: ["chi2"]
  impute_strategy: ["mean"]
