experiment_name: "knn_experiment2"
pipeline: "knn"
cv_folds: 15
grid_cv_folds: 3
seed: 17
pipeline_params:
  thresholds: [0.0001]
  n_neighbors: [5, 7, 9]
  power_parameter: [1, 2] # 1: Manhattan, 2: Euclidean
  impute_strategy: ["mean", "most_frequent"]
