experiment_name: "svm_linear_experiment"
pipeline: "svm_linear"
cv_folds: 15
grid_cv_folds: 3
seed: 17
pipeline_params:
  n_pca_components: [2, 5, 10]
  svm_regularization: [0.1, 1, 10, 100]
  impute_strategy: ["mean", "most_frequent"]
