experiment_name: "tree_experiment"
pipeline: "tree"
cv_folds: 15
grid_cv_folds: 3
seed: 17
pipeline_params:
  max_depth: [5, 10, 20, null]
  min_samples_split: [2, 5, 10]
  criterion: ['gini', 'entropy']
  impute_strategy: ["mean", "most_frequent"]
